### ISSUE TITLE
期望对于.net core 2.0的支持

### ISSUE THREAD

**Issue by chaiziqi** [jxnkwlp/Microsoft.Owin.Security.QQ-WebChat#3]
你好，非常感谢提供了好用的微信认证登录扩展包，.net core 2.0已正式发布，请问是否有升级到.net core 2.0的计划？非常期待您的升级成果，谢谢！

**Comment by jxnkwlp** [comment]
你好，已经 完成相关编码。 但是 因为暂时无法申请到相关APPKEY，所以，暂时 无法完成测试 。

**Comment by jxnkwlp** [comment]
已完成。 https://github.com/jxnkwlp/AspNetCore.AuthenticationQQ-WebChat
